---
# configure_kerberos_kdcs/tasks/configure_the_krb5_conf.yml

- name: 'Create krb5.conf'
  template:
    src: 'krb5_conf.j2'
    dest: "{{ path_to_krb5_conf }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  tags:
    - 'configuration'
