---
# configure_kerberos_kdcs/tasks/install_packages.yml

- name: 'Install Kerberos client packages'
  ansible.builtin.package:
    name: "{{ kerberos_client_packages }}"
    state: 'present'
  tags:
    - 'installation'
